export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'
export const SIGN_UP_FAIL = 'SIGN_UP_FAIL'

export const LOGOUT = 'LOGOUT'

export const CURRENT_USER_REQUEST = 'CURRENT_USER_REQUEST'
export const CURRENT_USER_SUCCESS = 'CURRENT_USER_SUCCESS'
export const CURRENT_USER_FAIL = 'CURRENT_REQUEST_FAIL'

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST'
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL'

export const SEND_CONFIRMATION_EMAIL_REQUEST = 'SEND_CONFIRMATION_EMAIL_REQUEST'
export const SEND_CONFIRMATION_EMAIL_SUCCESS = 'SEND_CONFIRMATION_EMAIL_SUCCESS'
export const SEND_CONFIRMATION_EMAIL_FAIL = 'SEND_CONFIRMATION_EMAIL_FAIL'

export const EMAIL_CONFIRMED_REQUEST = 'EMAIL_CONFIRMED_REQUEST'
export const EMAIL_CONFIRMED_SUCCESS = 'EMAIL_CONFIRMED_SUCCESS'
export const EMAIL_CONFIRMED_FAIL = 'EMAIL_CONFIRMED_FAIL'

export const RESET_CODE_REQUEST = 'RESET_CODE_REQUEST'
export const RESET_CODE_SUCCESS = 'RESET_CODE_SUCCESS'
export const RESET_CODE_FAIL = 'RESET_CODE_FAIL'

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL'
