export const LIST_COMMENTS_REQUEST = 'LIST_COMMENTS_REQUEST'
export const LIST_COMMENTS_SUCCESS = 'LIST_COMMENTS_SUCCESS'
export const LIST_COMMENTS_FAIL = 'LIST_COMMENTS_FAIL'

export const SINGLE_COMMENT_REQUEST = 'SINGLE_COMMENT_REQUEST'
export const SINGLE_COMMENT_FAIL = 'SINGLE_COMMENT_FAIL'
export const SINGLE_COMMENT_SUCCESS = 'SINGLE_COMMENT_SUCCESS'

export const ADD_COMMENT_REQUEST = 'ADD_COMMENT_REQUEST'
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS'
export const ADD_COMMENT_FAIL = 'ADD_COMMENT_FAIL'

export const EDIT_COMMENT_REQUEST = 'EDIT_COMMENT_REQUEST'
export const EDIT_COMMENT_SUCCESS = 'EDIT_COMMENT_SUCCESS'
export const EDIT_COMMENT_FAIL = 'EDIT_COMMENT_FAIL'

export const DELETE_COMMENT_REQUEST = 'DELETE_COMMENT_REQUEST'
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS'
export const DELETE_COMMENT_FAIL = 'DELETE_COMMENT_FAIL'
