export const POPULATE_FEED_REQUEST = 'POPULATE_FEED_REQUEST'
export const POPULATE_FEED_SUCCESS = 'POPULATE_FEED_SUCCESS'
export const POPULATE_FEED_FAIL = 'POPULATE_FEED_FAIL'

export const USER_POSTS_REQUEST = 'USER_POSTS_REQUEST'
export const USER_POSTS_SUCCESS = 'USER_POSTS_SUCCESS'
export const USER_POSTS_FAIL = 'USER_POSTS_FAIL'

export const SINGLE_POST_REQUEST = 'SINGLE_POST_REQUEST'
export const SINGLE_POST_SUCCESS = 'SINGLE_POST_SUCCESS'
export const SINGLE_POST_FAIL = 'SINGLE_POST_FAIL'

export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST'
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
export const CREATE_POST_FAIL = 'CREATE_POST_FAIL'

export const UPDATE_POST_REQUEST = 'UPDATE_POST_REQUEST'
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS'
export const UPDATE_POST_FAIL = 'UPDATE_POST_FAIL'

export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL'

export const LIKE_POST_REQUEST = 'LIKE_POST_REQUEST'
export const LIKE_POST_SUCCESS = 'LIKE_POST_SUCCESS'
export const LIKE_POST_FAIL = 'LIKE_POST_FAIL'

export const SHARE_POST_REQUEST = 'SHARE_POST_REQUEST'
export const SHARE_POST_SUCCESS = 'SHARE_POST_SUCCESS'
export const SHARE_POST_FAIL = 'SHARE_POST_FAIL'

export const LIKED_POSTS_REQUEST = 'LIKED_POSTS_REQUEST'
export const LIKED_POSTS_SUCCESS = 'LIKED_POSTS_SUCCESS'
export const LIKED_POSTS_FAIL = 'LIKED_POSTS_FAIL'

export const SHARED_POSTS_REQUEST = 'SHARED_POSTS_REQUEST'
export const SHARED_POSTS_SUCCESS = 'SHARED_POSTS_SUCCESS'
export const SHARED_POSTS_FAIL = 'SHARED_POSTS_FAIL'
